name: Test
on: [push]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: Test
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test
